default:
  course_title: "Reproducible Research Data and Project Management in R"
  hackpad_url: "http://bit.ly/acce21-notepad""
  course_dates: "April-May 2021"
  location: "Online"
  book_url: "http://annakrystalli.me/rrresearchACCE20/"
  bitly_url: "http://bit.ly/ACCE-book"
  output_dir: "_book"