on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  bookdown:
    name: Render-Book
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
  
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
  
      - name: Install pandoc
        run: |
           brew install pandoc
            
      - name: Query dependencies
        run: |
           install.packages('remotes')
           saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
           writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
  
      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: r-${{ hashFiles('.github/R-version') }}-1-
  
      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-
  
      - name: Install packages
        run: |
          remotes::install_deps(dependencies = TRUE)
          icons::download_fontawesome()
        shell: Rscript {0}
  
      - name: Render Slides
        run : |
          output_dir <- "_book"
          render_slides <- function(input_path, output_dir){
              
              output_format_obj <- xaringan::moon_reader(
                  css = c("default",  "assets/css/little_ak.css", "assets/css/little_ak-fonts.css"),
                  lib_dir = here::here(output_dir, "slides", "libs"),
                  seal = FALSE,
                  nature = list(beforeInit = "https://platform.twitter.com/widgets.js",
                                highlightStyle= "github",
                                highlightLines= TRUE,
                                countIncrementalSlides = FALSE)
              )
              
              
              rmarkdown::render(input = input_path,
                                output_dir = here::here(output_dir, "slides"),
                                output_format = output_format_obj,
                                params = list(course_title = "Reproducible Research Data and Project Management in R",
                                              date = "Apr-May 2021",
                                              location = "Online",
                                              book_url = "http://annakrystalli.me/rrresearchACCE20/",
                                              hackpad_url = "https://bit.ly/acce20-notepad",
                                              bitly_url= "http://bit.ly/ACCE-book"))
            
            fs::dir_copy(fs::path("slides", "assets"), 
                         fs::path(output_dir, "slides", "assets"),
                         overwrite = TRUE)
            fs::dir_copy(fs::path("files_to_copy"), 
                         fs::path(output_dir),
                         overwrite = TRUE)
                         
            # render slides
            slide_paths <- fs::dir_ls("slides", regex = ".Rmd")
            purrr::map(slide_paths, ~render_slides(.x, output_dir))
        shell: Rscript {0}
        
      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

# Need to first create an empty gh-pages branch
# see https://pkgdown.r-lib.org/reference/deploy_site_github.html
# and also add secrets for a GH_PAT and EMAIL to the repository
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@master
     - name: Download artifact
       uses: actions/download-artifact@v1.0.0
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          EMAIL: ${{ secrets.EMAIL }}               # must be a verified email
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/settings/tokens
       with:
          email: ${{ secrets.EMAIL }} 
          build_dir: _book/ 
          cname: annakrystalli.me
       
       